### ISSUE TITLE
Broken header/footer and images in https://asbp.ala.org.au/

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/asbp-hub#10]
If you are not aware, several images are broken in:
https://asbp.ala.org.au/

![image](https://user-images.githubusercontent.com/180085/178227490-dd00eff0-2536-4aeb-8263-51349f5131d0.png)

These pointing to https://www.seedpartnership.org.au/

**Comment by nickdos** [comment]
Thanks @vjrj - we are aware of this. The main Seed bank site was redeveloped but we were not provide resources to update the styling/branding and fix the broken images, etc., so it was left "as is". We are now working on a new hub that will replace this one.
