### ISSUE TITLE
Cloud Uplift (New Authentication + Grails 4 + Java 11)

### ISSUE THREAD

**Issue by jack-brinkman** [AtlasOfLivingAustralia/asbp-hub#9]
This issue tracks commits related to `cloud-uplift`.

**Please note that before running locally, the following needs to be completed:**

1. Clone the [biocache-hubs](https://github.com/AtlasOfLivingAustralia/biocache-hubs) repository, and check out the `cloud-uplift` branch.
2. Clone the [downloads-plugin](https://github.com/AtlasOfLivingAustralia/downloads-plugin) repository, and check out the `grails4` branch.
3. Clone the [ala-ws-plugin](https://github.com/AtlasOfLivingAustralia/ala-ws-plugin) repository.

Then, run the app via the terminal with the following command: `./gradlew clean bootRun`

Changes taken from [avh-hub/epic/cloud-uplift/develop](https://github.com/AtlasOfLivingAustralia/avh-hub/tree/epic/cloud-uplift/develop).

**Comment by sat01a** [comment]
@qifeng-bai - For latest plugin refer to this migration page - https://confluence.csiro.au/display/ALASD/OIDC+Migration+on+ALA+Applications
